name: Publish to PyPI (tags)

on:
  push:
    tags:
      - "v0.1.1"

permissions:
  contents: read
  id-token: write   # required for Trusted Publishing (no API token)

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: pip install build
      - run: python -m build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
